### ISSUE TITLE
[BUG] - Linux Dedicated Server doesn't generate the trader_config.yaml if not present.

### ISSUE THREAD

**Issue by Magnacoder** [sbtoonz/Trader_2.0#23] opened 2023-04-05 15:04 UTC
**Describe the bug**
I'm running on lloesche/valheim-server-docker . When I add Trader20.dll and don't include the yaml file on the dedicated server (I do this intentionally as I prefer to have the mods autogenerate defaults), I noticed that the mod did not produce the yaml file.

The code might be incomplete here [https://github.com/sbtoonz/Trader_2.0/blob/master/Trader2.0/ModCore.cs [line 80]](https://github.com/sbtoonz/Trader_2.0/blob/master/Trader2.0/ModCore.cs#L78-L81). 

```
            if (!File.Exists(Paths + Path.DirectorySeparatorChar + "trader_config.yaml"))
            {
                File.Create(Paths + Path.DirectorySeparatorChar + "trader_config.yaml").Close();
            }
```

**To Reproduce**
1. Set up a Linux Dedicated Server with Bepinex. I use lloesche/valheim-server-docker.
2. Install just Trader20.dll as a plugin, with no added yaml files. 
3. Run the server.
4. See the log output. You'll see "[Info   :   BepInEx] Loading [KnarrTheTrader 0.4.7]" then when the world loads: "[Error  :KnarrTheTrader] There was an issue loading your trader_config.yaml. [Error  :KnarrTheTrader] Please check your config entries for spelling and format!" over and over again. 

**Expected behavior**
I would expect the mod to be able to self generate the missing trader_config yaml with a default version, if not present.

 - OS:  Linux 0e6e581be63f 5.19.17-Unraid
 - Version KnarrTheTrader 0.4.7
 - Bepinex Version 5.4.2102
 - Valheim Version 0.214.305
 - Server

**Comment by sbtoonz** [comment] 2023-04-05 15:05
I will take a look
It just produces a empty YML if none found

the EXAMPLE_trader_config.yml is a populated file that is offered for an example

**Comment by sbtoonz** [comment] 2023-04-05 15:20
https://github.com/lloesche/valheim-server-docker/issues/614

have a feeling this is the real root cause

**Comment by Magnacoder** [comment] 2023-04-06 15:40
Btw,  lloesche/valheim-server-docker is starred by 1.6K people, so I would imagine a solution here would help adoption for those who are using it like me. Hopefully, lloesche responds to my issue and request he _not_ put the plugin preload folder under config, but we'll see how long that takes.

**Comment by sbtoonz** [comment] 2023-04-12 20:33
[](https://docs.bepinex.dev/master/api/BepInEx.Paths.html)

I do not know how to start explaining this

I use bepinex to resolve the path of the configs folder

Bepinex itself will take note of where its config files are 
You call to it's API in order to gain this path in a string and use it for storage 

as you can see here that XRay vision does this
https://github.com/AzumattDev/XRayVision/blob/master/XRayVision.cs#L193
https://github.com/AzumattDev/XRayVision/blob/master/XRayVision.cs#L28


Hre you can see I follow the exact same coding style

https://github.com/sbtoonz/Trader_2.0/blob/master/Trader2.0/ModCore.cs#L36
https://github.com/sbtoonz/Trader_2.0/blob/master/Trader2.0/ModCore.cs#L80

**Comment by sbtoonz** [comment] 2023-04-12 21:03
Just installed Lloesche docker
set BEPINEX true
let it load up 

empty yaml produced in config folder as intended by design......
indeed it cant read an empty YAML file...  so it complains 

shutdown server
replaced the trader_config.yaml with EXAMPLE_trader_config.yaml (by renaming EXAMPLE one) 

Rebooted server
Now there is no issue reading my YAML file well..because it has content


closing this as it is a non issue and un replicable

**Closed by sbtoonz** 2023-04-12 21:03 UTC
Labels: bug
